#!/bin/sh
set -e

# -----------------------------------------------
# Socrata
# -----------------------------------------------

# Get the list of 4x4s
./socrata_datasets_download.sh
./socrata_datasets_viewids.py

# Download metadata
./socrata_views_download.sh

# Download spreadsheets
./socrata_rows_download.sh

# Upload them to S3
./socrata_rows_s3.sh

# -----------------------------------------------
# Collabfinder
# -----------------------------------------------

# Download the project pages.
./collabfinder_project_download.sh
